name: 'terraform-plan'
description: 'launch terraform init, validate and plan check terraform scripts'

inputs:
  working_dir:
    description: 'Working directory'
    default: "."
  tfbackend_file:
    description: 'Path and the backend file that will be used by terraform init'
    required: true
  tfvars_file:
    description: 'Path and the backend file that will be used by terraform plan'
    required: true
  plan_args:
    description: 'Terraform args to pass to the plan command'
    default: ""
    required: false
    

runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@v3

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v2

  - name: Terraform init
    shell: bash
    run: terraform init -backend-config=${{ inputs.tfbackend_file }}
    working-directory: ${{ inputs.working_dir }}
    
  - name: Terraform validate
    shell: bash
    run: terraform validate
    working-directory: ${{ inputs.working_dir }}

  - name: Terraform plan
    shell: bash
    run: terraform plan -var-file=${{ inputs.tfvars_file }} ${{ inputs.plan_args }}
    working-directory: ${{ inputs.working_dir }}
