name: 'terraform-plan'
description: 'launch terraform init, validate and plan check terraform scripts'

inputs:
  env:
    description: 'Environment to test. will use the corresponding {$env}/vars.tfvars and {$env}/backend.tfvars files'
    required: true
  plan_args:
    description: 'Terraform args to pass to the plan command'
    default: ""
    required: false
    
runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@v3

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v2

  - name: Terraform init
    shell: bash
    run: terraform init -backend-config="./env/${{ inputs.env }}/config.tfbackend"
    
  - name: Terraform validate
    shell: bash
    run: terraform validate

  - name: Terraform plan
    shell: bash
    run: terraform plan -var-file=./env/${{ inputs.env }}/vars.tfvars ${{ inputs.plan_args }}
