name: release-please
description: "Release Please automates releases for your projects using conventional commits."

inputs:
  RELEASE_PLEASE_TOKEN:
    description: "The token to use for authenticating with GitHub."
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: google-github-actions/release-please-action@v3
    with:
      command: manifest
      token: ${{ inputs.RELEASE_PLEASE_TOKEN }}
