name: release-please
description: "Release Please automates releases for your projects using conventional commits."

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: google-github-actions/release-please-action@v3
    with:
      command: manifest
