name: 'terraform-validate'
description: 'launch terraform init and validate'

runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@v3

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v2

  - name: Terraform init
    shell: bash
    run: terraform init -backend-config=${{ inputs.tfbackend_file }}

  - name: Terraform validate
    shell: bash
    run: terraform validate
