name: dev-deployment

on:
  workflow_run:
    workflows: ["delivery"]
    branches: [cicd] # TODO: to change into "main"
    types:
      - completed

jobs:
  deployment:
    uses: Foxon-Consulting/github-actions/.github/workflows/simple_deployment.yml@cicd
