name: Delivery

on:
  workflow_call:
    inputs:
      download-artifact-name:
        description: 'Name of artifact to download'
        required: true
        type: string
      deploy-image-name:
        description: 'Name of image to deploy'
        required: true
        type: string
      deploy-image-tag:
        description: 'Tag of image to deploy'
        required: false
        type: string
        default: ${{ github.sha }}

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.download-artifact-name }}
          path: /tmp
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Load image
        run: |
          docker load --input /tmp/${{ inputs.download-artifact-name }}.tar
      # Tag image with git sha if not a tag, with the tag if it is a tag
      # - name: Tag image
      #   run: |
      #     echo $GITHUB_REF_TYPE
      #     if [ $GITHUB_REF_TYPE == 'tag' ]; then
      #       docker tag ${{ inputs.deploy-image-name }}:temp foxonconsulting/${{ inputs.deploy-image-name }}:${GITHUB_REF_NAME}
      #       docker push foxonconsulting/${{ inputs.deploy-image-name }}:${GITHUB_REF_NAME}
      #     else
      #       docker tag ${{ inputs.deploy-image-name }}:temp foxonconsulting/${{ inputs.deploy-image-name }}:${GITHUB_SHA}
      #       docker push foxonconsulting/${{ inputs.deploy-image-name }}:${GITHUB_SHA}
      #     fi
      - name: Tag image
        run: |
          docker tag ${{ inputs.deploy-image-name }}:temp foxonconsulting/${{ inputs.deploy-image-name }}:${{ inputs.deploy-image-tag }}
          docker push foxonconsulting/${{ inputs.deploy-image-name }}:${{ inputs.deploy-image-tag }}
