name: Docker Build

on:
  workflow_call:
    inputs:
      dockerfile-path:
        description: 'Path to Dockerfile'
        required: true
        type: string
      download-artifact-name:
        description: 'Name of artifact to download before running docker build. Example: output of npm build. If not given, no download is done'
        required: false
        type: string
      upload-artifact-name:
        description: 'Name of the image artifact to upload. If not given, no upload is done'
        required: false
        type: string

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        if: ${{ inputs.download-artifact-name != null }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.download-artifact-name }}
          path: ./out/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile-path }}
          push: false
          tags: docker-image:temp
          outputs: type=docker,dest=/tmp/docker-image.tar

      - name: Upload artifact
        if: ${{ inputs.upload-artifact-name != null }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.upload-artifact-name }}
          path: /tmp/docker-image.tar
