name: integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "**"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: pre-commit
        uses: Foxon-Consulting/github-actions/integration/actions/pre-commit@cicd
  simple_integration:
    uses: Foxon-Consulting/github-actions/.github/workflows/simple_integration.yml@cicd
