name: Delivery

on:
  workflow_call:
    secrets:
      docker-username:
        required: true
      docker-password:
        required: true
    inputs:
      deploy-image-name:
        description: 'Name of image to deploy'
        required: true
        type: string
        default: 'app-deploy-img'

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.deploy-image-name }}
          path: /tmp
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker-username}}
          password: ${{ secrets.docker-password }}
      - name: Load image
        run: |
          docker load --input /tmp/${{ inputs.deploy-image-name }}.tar
      # Tag image with git sha if not a tag, with the tag if it is a tag
      - name: Tag image
        run: |
          if [ $GITHUB_REF_TYPE == 'tag' ]; then
            docker tag ${{ inputs.deploy-image-name }}:temp foxonconsulting/${{ inputs.deploy-image-name }}:${GITHUB_REF_NAME}
            docker push foxonconsulting/${{ inputs.deploy-image-name }}:${GITHUB_REF_NAME}
          else
            docker tag ${{ inputs.deploy-image-name }}:temp foxonconsulting/${{ inputs.deploy-image-name }}:${GITHUB_SHA}
            docker push foxonconsulting/${{ inputs.deploy-image-name }}:${GITHUB_SHA}
          fi
