name: Integration

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Name of artifact to download'
        required: true
        type: string
        default: 'app-artifact'
      deploy-image-name: 
        description: 'Name of image to deploy'
        required: true
        type: string
        default: 'app-deploy-img'

jobs:
  build:
    runs-on: ubuntu-latest
    container: lizzieb1416/node-image:1.0.0 ## GHANGER
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build with Next.js
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: ./out/

  test:
    runs-on: ubuntu-latest
    container: lizzieb1416/node-image:1.0.0 ## GHANGER
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install
        run: npm ci
      - name: test
        run: npm test

  build-image:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: ./out/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ inputs.deploy-image-name }}:temp
          outputs: type=docker,dest=/tmp/${{ inputs.deploy-image-name }}.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.deploy-image-name }}
          path: /tmp/${{ inputs.deploy-image-name }}.tar



