name: Integration

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node version to use'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container: lizzieb1416/node-image:1.0.0 ## GHANGER
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build with Next.js
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: next-base-project-artifact
          path: ./out/

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    container: lizzieb1416/node-image:1.0.0 ## GHANGER
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install
        run: npm ci
      - name: test
        run: npm test
