name: Delivery

on:
  workflow_call:

jobs:
  python:
    # echo Hello World
    runs-on: ubuntu-latest
    steps:
      - name: simple
        uses: Foxon-Consulting/github-actions/delivery/actions/simple@main
