name: Integration

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version to use'
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}
      - name: update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install application
        run: |
          pip install .
      - name: Install CI dependencies
        run: |
          pip install --no-input flake8 black tox pytest
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Check formatting with black
        uses: psf/black@stable
      - name: Test with tox
        run: |
          tox
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}
      - name: update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install build dependencies
        run: |
          pip install build
      - name: build wheel
        run: |
          python -m build --wheel
