name: Integration

on:
  workflow_call:
    inputs:
      env:
        description: 'Environment to run against'
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: simple
        uses: Foxon-Consulting/github-actions/integration/terraform/validate@main
        with:
          env: ${{ github.event.inputs.environments }}
