name: Integration

on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: simple
        uses: Foxon-Consulting/github-actions/integration/terraform/validate@main
